workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always


stages:
  - staging
  - production


default:
  after_script:
    - sudo rm -r ~/builds/
    - sudo nginx -t
    - sudo systemctl restart nginx


deploy-to-stage:
    stage: staging
    script:
      - cd $TEST_STATIC_DIR
      - git pull

    tags:
      - shell


deploy-to-prod:
    stage: production
    when: manual
    script:
      - cd $STATIC_DIR
      - git pull

    tags:
      - ssh

